### ISSUE TITLE
Hijacking a stream

### ISSUE THREAD

**Issue by rnapier** [SlyMarbo/spdy#86]
SPDY streams can be bidirectional, and I'd like to communicate in both directions on a single stream. Currently the request and response code force the request body to be complete prior to processing the data (both because `conn.Request` always close the requester body, and because `responseStream.Run` waits for the request FIN before proceeding.

Is it possible to hijack the stream so I can treat it as a ReadWriter on both sides?

**Comment by SlyMarbo** [comment]
I don't think it's possible, no, since you would need to start a request and then hijack the stream before the request completes, which doesn't really make sense. You can hijack the connection as a whole, but then you lose everything.

Sorry I've been away for the last week and a bit, I'm getting up to speed on the other issues now.
